# frozen_string_literal: true

require "rake/extensiontask"
require "rake/testtask"

Rake::ExtensionTask.new("c") do |ext|
  ext.lib_dir = "lib/demos"
end

Rake::ExtensionTask.new("rust_rbsys") do |ext|
  ext.lib_dir = "lib/demos"
end

Rake::ExtensionTask.new("rust_magnus") do |ext|
  ext.lib_dir = "lib/demos"
end

Rake::ExtensionTask.new("rust_magnus_geo") do |ext|
  ext.lib_dir = "lib/demos"
end

Rake::TestTask.new("test:fast") do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.verbose = true
end

desc "Run all tests"
task test: ["compile", "test:fast"]

task default: :test
